# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8feabdc2736f757d79a93604c99e97f67d60d03cb50b795bbf6b59f97e09c81291df31e65009e6fbd372e65c83d7954c159f0d11accc57b6b540def50c80e987

test:
  secret_key_base: f9a44242c24255b0b3fbd57c53ca2385e0c18b2807075958ff258aaf189bab472cbbb8f05217f8902b26a308e46f3be4a04efcef69672794dacc2a55ee9532bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
